# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Display OLED SH1106 1.3"
CONFIG_ZMK_DISPLAY=y
CONFIG_DISPLAY=y

# Fila de trabalho dedicada para o display (choice symbol — vai no .conf)
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Fonte padrão
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Sem sleep no dongle (conectado via USB)
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_EXT_POWER=n
