# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Display OLED SSD1306
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_DISPLAY=y

# Fonte padrão
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Sem sleep no dongle (conectado via USB)
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_EXT_POWER=n
